services:
  simple_todo_app:
    container_name: simple_todo_application
    # Download from docker hub
    image: ortolanph/simple_todos:1.0.0
    # Use local image
    # build: .
    ports:
      - "10132:8080"
    networks:
      - simple_todo_network

networks:
  simple_todo_network:
    driver: bridge
