name: simple_todo
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.0-173.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_injector: ^2.1.1
  build_runner: ^2.4.13
  cupertino_icons: ^1.0.8
  equatable: ^2.0.8
  flutter_spinkit: ^5.2.2
  font_awesome_flutter: ^10.12.0
  format: ^1.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_serializable: ^6.8.0
  uuid: ^4.5.2
  provider: ^6.1.5+1
  intl: ^0.20.2
  path_provider: ^2.1.5
  pdf: ^3.11.3
  json_annotation: ^4.9.0
  logging: ^1.3.0
  csv: ^7.1.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
